export const languageConfig = [
  { code: "ar", name: "العربية", enabled: true, desc: "阿拉伯语" },
  { code: "bg", name: "Български", enabled: true, desc: "保加利亚语" },
  { code: "bn", name: "বাংলা", enabled: true, desc: "孟加拉语" },
  { code: "cs", name: "Čeština", enabled: true, desc: "捷克语" },
  { code: "da", name: "Dansk", enabled: true, desc: "丹麦语" },
  { code: "de", name: "Deutsch", enabled: true, desc: "德语" },
  { code: "el", name: "Ελληνικά", enabled: true, desc: "希腊语" },
  { code: "en", name: "English", enabled: true, desc: "英语" },
  { code: "es", name: "Español", enabled: true, desc: "西班牙语" },
  { code: "fa", name: "فارسی", enabled: true, desc: "波斯语" },
  { code: "fi", name: "Suomi", enabled: true, desc: "芬兰语" },
  { code: "fr", name: "Français", enabled: true, desc: "法语" },
  { code: "he", name: "עברית", enabled: true, desc: "希伯来语" },
  { code: "hi", name: "हिन्दी", enabled: true, desc: "印地语" },
  { code: "hu", name: "Magyar", enabled: true, desc: "匈牙利语" },
  { code: "id", name: "Bahasa Indonesia", enabled: true, desc: "印度尼西亚语" },
  { code: "it", name: "Italiano", enabled: true, desc: "意大利语" },
  { code: "ja", name: "日本語", enabled: true, desc: "日语" },
  { code: "ko", name: "한국어", enabled: true, desc: "韩语" },
  { code: "ms", name: "Bahasa Melayu", enabled: true, desc: "马来语" },
  { code: "nl", name: "Nederlands", enabled: true, desc: "荷兰语" },
  { code: "no", name: "Norsk", enabled: true, desc: "挪威语" },
  { code: "pl", name: "Polski", enabled: true, desc: "波兰语" },
  { code: "pt", name: "Português", enabled: true, desc: "葡萄牙语" },
  { code: "ro", name: "Română", enabled: true, desc: "罗马尼亚语" },
  { code: "ru", name: "Русский", enabled: true, desc: "俄语" },
  { code: "sk", name: "Slovenčina", enabled: true, desc: "斯洛伐克语" },
  { code: "sl", name: "Slovenščina", enabled: true, desc: "斯洛文尼亚语" },
  { code: "sr", name: "Српски", enabled: true, desc: "塞尔维亚语" },
  { code: "sv", name: "Svenska", enabled: true, desc: "瑞典语" },
  { code: "th", name: "ไทย", enabled: true, desc: "泰语" },
  { code: "tr", name: "Türkçe", enabled: true, desc: "土耳其语" },
  { code: "uk", name: "Українська", enabled: true, desc: "乌克兰语" },
  { code: "uz", name: "O‘zbek", enabled: true, desc: "乌兹别克语" },
  { code: "vi", name: "Tiếng Việt", enabled: true, desc: "越南语" },
  { code: "zh", name: "简体中文", enabled: true, desc: "中文" },
  { code: "zh-Hant", name: "繁體中文", enabled: true, desc: "繁体中文" },
];
